# Generated by Django 4.1.6 on 2023-02-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='work',
            name='codeUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Frameworks', to='portfolio.language')),
            ],
        ),
    ]
