# Generated by Django 4.1.7 on 2023-02-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
