# Generated by Django 4.1.7 on 2023-03-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_work_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='texture',
            field=models.IntegerField(choices=[(0, 'Python'), (1, 'Typescript'), (1000, 'Blank')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='texture',
            field=models.IntegerField(choices=[(0, 'Python'), (1, 'Typescript'), (1000, 'Blank')], default=0),
            preserve_default=False,
        ),
    ]
