# Generated by Django 4.1.7 on 2023-03-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_framework_texture_language_texture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='texture',
            field=models.IntegerField(choices=[(0, 'Python'), (1, 'Typescript'), (2, 'Css'), (3, 'Django'), (4, 'Express'), (5, 'Git'), (6, 'Html'), (7, 'Javascript'), (8, 'Markdown'), (9, 'React'), (10, 'Sql'), (11, 'Threejs'), (1000, 'Blank')]),
        ),
        migrations.AlterField(
            model_name='language',
            name='texture',
            field=models.IntegerField(choices=[(0, 'Python'), (1, 'Typescript'), (2, 'Css'), (3, 'Django'), (4, 'Express'), (5, 'Git'), (6, 'Html'), (7, 'Javascript'), (8, 'Markdown'), (9, 'React'), (10, 'Sql'), (11, 'Threejs'), (1000, 'Blank')]),
        ),
    ]
